set modeline
set modelines=5
set textwidth=60

execute pathogen#infect()

filetype plugin indent on
syntax on

" Spell check on
set spell spelllang=en_us
setlocal spell spelllang=en_us

" Spelling
highlight clear SpellBad
highlight SpellBad term=standout ctermfg=1 term=underline cterm=underline
highlight clear SpellCap
highlight SpellCap term=underline cterm=underline
highlight clear SpellRare
highlight SpellRare term=underline cterm=underline
highlight clear SpellLocal
highlight SpellLocal term=underline cterm=underline
